// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/buytheway/protocol/addressee.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AddresseeInfo;
@class PageDataRequest;
@class RetCode;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - AddresseeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface AddresseeRoot : GPBRootObject
@end

#pragma mark - UserCommonAddresseeSaveRequest

typedef GPB_ENUM(UserCommonAddresseeSaveRequest_FieldNumber) {
  UserCommonAddresseeSaveRequest_FieldNumber_Addressee = 2,
};

/**
 * 1.1用户常用收件人信息保存（新增，或者修改都调用此接口！！，addressee有id就是修改） /addressee/saveCommonAddresses
 **/
@interface UserCommonAddresseeSaveRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) AddresseeInfo *addressee;
/** Test to see if @c addressee has been set. */
@property(nonatomic, readwrite) BOOL hasAddressee;

@end

#pragma mark - GetUserAddresseeListRequest

typedef GPB_ENUM(GetUserAddresseeListRequest_FieldNumber) {
  GetUserAddresseeListRequest_FieldNumber_Req = 1,
};

/**
 * 2.1 用户常用地址联系人列表获取  /addressee/getCommonAddress
 **/
@interface GetUserAddresseeListRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PageDataRequest *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@end

#pragma mark - GetUserAddresseeListResponse

typedef GPB_ENUM(GetUserAddresseeListResponse_FieldNumber) {
  GetUserAddresseeListResponse_FieldNumber_RetCode = 1,
  GetUserAddresseeListResponse_FieldNumber_AddresseeArray = 2,
};

/**
 * 2.2
 **/
@interface GetUserAddresseeListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 返回常用联系人地址列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<AddresseeInfo*> *addresseeArray;
/** The number of items in @c addresseeArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger addresseeArray_Count;

@end

#pragma mark - DeleteUserAddresseeRequest

typedef GPB_ENUM(DeleteUserAddresseeRequest_FieldNumber) {
  DeleteUserAddresseeRequest_FieldNumber_AddresseeId = 1,
};

/**
 * 3.1 删除地址 /addressee/delete
 **/
@interface DeleteUserAddresseeRequest : GPBMessage

/** 返回常用联系人地址列表 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *addresseeId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
