// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/buytheway/protocol/buy.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AddressInfo;
@class AddresseeInfo;
@class BuyTripTaskInfo;
@class Money;
@class OrderInfo;
@class PageDataRequest;
@class RetCode;
@class SellTripTask;
@class SpaceInfo;
GPB_ENUM_FWD_DECLARE(OrderStatus);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BuyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BuyRoot : GPBRootObject
@end

#pragma mark - BuyTripTaskRequest

typedef GPB_ENUM(BuyTripTaskRequest_FieldNumber) {
  BuyTripTaskRequest_FieldNumber_TaskInfo = 1,
};

/**
 * 1.1 买家发布信息 想购买的行程服务  /buy/tripTask
 **/
@interface BuyTripTaskRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BuyTripTaskInfo *taskInfo;
/** Test to see if @c taskInfo has been set. */
@property(nonatomic, readwrite) BOOL hasTaskInfo;

@end

#pragma mark - BuyTripTaskResponse

typedef GPB_ENUM(BuyTripTaskResponse_FieldNumber) {
  BuyTripTaskResponse_FieldNumber_RetCode = 1,
  BuyTripTaskResponse_FieldNumber_BuyTripTaskId = 2,
};

/**
 * 1.2 买家发布任务后成功 返回买家任务id
 **/
@interface BuyTripTaskResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 需求发布成功后会生成一个id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *buyTripTaskId;

@end

#pragma mark - MarrySellTripTaskListRequest

typedef GPB_ENUM(MarrySellTripTaskListRequest_FieldNumber) {
  MarrySellTripTaskListRequest_FieldNumber_BuyTripTaskId = 2,
};

/**
 * 2.1 根据/buy/tripTask取回的id去匹配卖家发布列表
 * 接口地址：buy/marrySellTripTaskList
 **/
@interface MarrySellTripTaskListRequest : GPBMessage

/** 需求发布成功后会生成一个id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *buyTripTaskId;

@end

#pragma mark - MarrySellTripTaskListResponse

typedef GPB_ENUM(MarrySellTripTaskListResponse_FieldNumber) {
  MarrySellTripTaskListResponse_FieldNumber_RetCode = 1,
  MarrySellTripTaskListResponse_FieldNumber_MarrySellTripTaskArray = 2,
  MarrySellTripTaskListResponse_FieldNumber_BuyTripTaskid = 3,
};

/**
 * 2.2
 **/
@interface MarrySellTripTaskListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 匹配的行程列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SellTripTask*> *marrySellTripTaskArray;
/** The number of items in @c marrySellTripTaskArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger marrySellTripTaskArray_Count;

/** 本次匹配到的行程 所属的任务id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *buyTripTaskid;

@end

#pragma mark - GetBuyTripTaskListRequest

typedef GPB_ENUM(GetBuyTripTaskListRequest_FieldNumber) {
  GetBuyTripTaskListRequest_FieldNumber_Req = 1,
};

/**
 * 3.1 取买家自己发布的需求列表 buy/getBuyTripTaskList
 **/
@interface GetBuyTripTaskListRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PageDataRequest *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@end

#pragma mark - GetBuyTripTaskListResponse

typedef GPB_ENUM(GetBuyTripTaskListResponse_FieldNumber) {
  GetBuyTripTaskListResponse_FieldNumber_RetCode = 1,
  GetBuyTripTaskListResponse_FieldNumber_TaskListArray = 2,
};

/**
 * 3.2返回
 **/
@interface GetBuyTripTaskListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 匹配的行程列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BuyTripTaskInfo*> *taskListArray;
/** The number of items in @c taskListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger taskListArray_Count;

@end

#pragma mark - BuyMarrySellTripTaskRequest

typedef GPB_ENUM(BuyMarrySellTripTaskRequest_FieldNumber) {
  BuyMarrySellTripTaskRequest_FieldNumber_SellTripTaskid = 1,
  BuyMarrySellTripTaskRequest_FieldNumber_BuyTripTaskid = 2,
};

/**
 * 4.1 买家预约行程 请求 buy/buyMarrySellTripTask
 **/
@interface BuyMarrySellTripTaskRequest : GPBMessage

/** 卖家的行程任务 id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sellTripTaskid;

/** 买家任务id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *buyTripTaskid;

@end

#pragma mark - BuyMarrySellTripTaskRespons

typedef GPB_ENUM(BuyMarrySellTripTaskRespons_FieldNumber) {
  BuyMarrySellTripTaskRespons_FieldNumber_RetCode = 1,
  BuyMarrySellTripTaskRespons_FieldNumber_OrderId = 2,
};

/**
 * 4.2 预约行程  返回
 **/
@interface BuyMarrySellTripTaskRespons : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 返回预约id 即 orderId 、、后台会生成预约订单记录（建立卖家买家行程关联关系） 状态为已预约 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@end

#pragma mark - GetBuyOrderListRequest

typedef GPB_ENUM(GetBuyOrderListRequest_FieldNumber) {
  GetBuyOrderListRequest_FieldNumber_OrderStutus = 1,
  GetBuyOrderListRequest_FieldNumber_Req = 2,
};

/**
 * 5.1 买家获得自己的订单列表状态（从预约开始） /buy/getOrderList
 **/
@interface GetBuyOrderListRequest : GPBMessage

@property(nonatomic, readwrite) enum OrderStatus orderStutus;

@property(nonatomic, readwrite, strong, null_resettable) PageDataRequest *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@end

/**
 * Fetches the raw value of a @c GetBuyOrderListRequest's @c orderStutus property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t GetBuyOrderListRequest_OrderStutus_RawValue(GetBuyOrderListRequest *message);
/**
 * Sets the raw value of an @c GetBuyOrderListRequest's @c orderStutus property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGetBuyOrderListRequest_OrderStutus_RawValue(GetBuyOrderListRequest *message, int32_t value);

#pragma mark - GetBuyOrderListResponse

typedef GPB_ENUM(GetBuyOrderListResponse_FieldNumber) {
  GetBuyOrderListResponse_FieldNumber_RetCode = 1,
  GetBuyOrderListResponse_FieldNumber_OrderListArray = 2,
};

/**
 * 5.2 买家获得自己的订单列表返回
 **/
@interface GetBuyOrderListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OrderInfo*> *orderListArray;
/** The number of items in @c orderListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger orderListArray_Count;

@end

#pragma mark - BuyTripTaskInfo

typedef GPB_ENUM(BuyTripTaskInfo_FieldNumber) {
  BuyTripTaskInfo_FieldNumber_BuyTripTaskId = 1,
  BuyTripTaskInfo_FieldNumber_BuySpace = 2,
  BuyTripTaskInfo_FieldNumber_SpaceImageArray = 3,
  BuyTripTaskInfo_FieldNumber_StartAddresseeInfo = 4,
  BuyTripTaskInfo_FieldNumber_EndAddressInfo = 5,
  BuyTripTaskInfo_FieldNumber_DeadLineTime = 6,
  BuyTripTaskInfo_FieldNumber_BudgetMoney = 7,
};

/**
 * 买家发布的任务 实体
 **/
@interface BuyTripTaskInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *buyTripTaskId;

/** 买家需要寄送的货物 规格重量 */
@property(nonatomic, readwrite, strong, null_resettable) SpaceInfo *buySpace;
/** Test to see if @c buySpace has been set. */
@property(nonatomic, readwrite) BOOL hasBuySpace;

/** 包裹照片 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *spaceImageArray;
/** The number of items in @c spaceImageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger spaceImageArray_Count;

/** 买家 包裹所在地址 寄送人信息 */
@property(nonatomic, readwrite, strong, null_resettable) AddresseeInfo *startAddresseeInfo;
/** Test to see if @c startAddresseeInfo has been set. */
@property(nonatomic, readwrite) BOOL hasStartAddresseeInfo;

/** 买家 包裹需要寄到的地址 收件人信息 */
@property(nonatomic, readwrite, strong, null_resettable) AddresseeInfo *endAddressInfo;
/** Test to see if @c endAddressInfo has been set. */
@property(nonatomic, readwrite) BOOL hasEndAddressInfo;

/** 买家要求的最迟的货物寄到目的地的时间 */
@property(nonatomic, readwrite) int64_t deadLineTime;

/** 预算价格 ？  币种转换 得考虑 系统子酸 ，到时候这个用一个实体，价格跟币种绑定使用 */
@property(nonatomic, readwrite, strong, null_resettable) Money *budgetMoney;
/** Test to see if @c budgetMoney has been set. */
@property(nonatomic, readwrite) BOOL hasBudgetMoney;

@end

#pragma mark - SellTripTask

typedef GPB_ENUM(SellTripTask_FieldNumber) {
  SellTripTask_FieldNumber_SellTripTaskid = 1,
  SellTripTask_FieldNumber_StartAddress = 2,
  SellTripTask_FieldNumber_EndAddressInfo = 3,
  SellTripTask_FieldNumber_BeginTime = 4,
  SellTripTask_FieldNumber_EndTime = 5,
  SellTripTask_FieldNumber_ConsignSpace = 6,
  SellTripTask_FieldNumber_HandbagSpace = 7,
};

/**
 * 卖家的行程任务
 **/
@interface SellTripTask : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *sellTripTaskid;

/** 卖家行程开始地址 */
@property(nonatomic, readwrite, strong, null_resettable) AddressInfo *startAddress;
/** Test to see if @c startAddress has been set. */
@property(nonatomic, readwrite) BOOL hasStartAddress;

/** 卖家行程结束地址 */
@property(nonatomic, readwrite, strong, null_resettable) AddresseeInfo *endAddressInfo;
/** Test to see if @c endAddressInfo has been set. */
@property(nonatomic, readwrite) BOOL hasEndAddressInfo;

/** 卖家行程开始时间 */
@property(nonatomic, readwrite) int64_t beginTime;

/** 卖家行程结束时间 */
@property(nonatomic, readwrite) int64_t endTime;

/** 行程任务空间 */
@property(nonatomic, readwrite, strong, null_resettable) SpaceInfo *consignSpace;
/** Test to see if @c consignSpace has been set. */
@property(nonatomic, readwrite) BOOL hasConsignSpace;

/** 手提包的space */
@property(nonatomic, readwrite, strong, null_resettable) SpaceInfo *handbagSpace;
/** Test to see if @c handbagSpace has been set. */
@property(nonatomic, readwrite) BOOL hasHandbagSpace;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
