// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/buytheway/protocol/buy.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AddressInfo;
@class AddresseeInfo;
@class BuyTaskInfo;
@class OrderInfo;
@class PageDataRequest;
@class RetCode;
@class SellTripTask;
@class SpaceInfo;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BuyRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface BuyRoot : GPBRootObject
@end

#pragma mark - BuyTripTaskRequest

typedef GPB_ENUM(BuyTripTaskRequest_FieldNumber) {
  BuyTripTaskRequest_FieldNumber_TaskInfo = 1,
};

/**
 * 1.1 买家发布信息 想购买的行程服务  /buy/tripTask
 **/
@interface BuyTripTaskRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) BuyTaskInfo *taskInfo;
/** Test to see if @c taskInfo has been set. */
@property(nonatomic, readwrite) BOOL hasTaskInfo;

@end

#pragma mark - BuyTripTaskResponse

typedef GPB_ENUM(BuyTripTaskResponse_FieldNumber) {
  BuyTripTaskResponse_FieldNumber_RetCode = 1,
  BuyTripTaskResponse_FieldNumber_BuyId = 2,
};

/**
 * 1.2 买家发布任务后匹配的卖家行程列表
 **/
@interface BuyTripTaskResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 需求发布成功后会生成一个id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *buyId;

@end

#pragma mark - GetMatchSaleTaskRequest

typedef GPB_ENUM(GetMatchSaleTaskRequest_FieldNumber) {
  GetMatchSaleTaskRequest_FieldNumber_BuyId = 2,
};

/**
 * 2.1 根据/buy/tripTask取回的id去匹配卖家发布列表
 * 接口地址：buy/getMatchList
 **/
@interface GetMatchSaleTaskRequest : GPBMessage

/** 需求发布成功后会生成一个id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *buyId;

@end

#pragma mark - GetMatchSaleTaskResponse

typedef GPB_ENUM(GetMatchSaleTaskResponse_FieldNumber) {
  GetMatchSaleTaskResponse_FieldNumber_RetCode = 1,
  GetMatchSaleTaskResponse_FieldNumber_MarrySellTripTaskArray = 2,
};

/**
 * 2.2
 **/
@interface GetMatchSaleTaskResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 匹配的行程列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<SellTripTask*> *marrySellTripTaskArray;
/** The number of items in @c marrySellTripTaskArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger marrySellTripTaskArray_Count;

@end

#pragma mark - GetSellTripTaskListRequest

typedef GPB_ENUM(GetSellTripTaskListRequest_FieldNumber) {
  GetSellTripTaskListRequest_FieldNumber_Req = 1,
};

/**
 * 3.1 取买家自己发布的需求列表 buy/getMyTripTaskList
 **/
@interface GetSellTripTaskListRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) PageDataRequest *req;
/** Test to see if @c req has been set. */
@property(nonatomic, readwrite) BOOL hasReq;

@end

#pragma mark - GetSellTripTaskListRequestRespons

typedef GPB_ENUM(GetSellTripTaskListRequestRespons_FieldNumber) {
  GetSellTripTaskListRequestRespons_FieldNumber_RetCode = 1,
  GetSellTripTaskListRequestRespons_FieldNumber_TaskListArray = 2,
};

/**
 * 3.2返回
 **/
@interface GetSellTripTaskListRequestRespons : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 匹配的行程列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<BuyTaskInfo*> *taskListArray;
/** The number of items in @c taskListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger taskListArray_Count;

@end

#pragma mark - BuyMarrySellTripTaskRequest

typedef GPB_ENUM(BuyMarrySellTripTaskRequest_FieldNumber) {
  BuyMarrySellTripTaskRequest_FieldNumber_SellTripTaskid = 1,
  BuyMarrySellTripTaskRequest_FieldNumber_BuyUserBizId = 2,
};

/**
 * 4.1 买家预约行程 请求 buy/buyMarrySellTripTask
 **/
@interface BuyMarrySellTripTaskRequest : GPBMessage

/** 卖家的行程任务 id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *sellTripTaskid;

/** 买家用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *buyUserBizId;

@end

#pragma mark - BuyMarrySellTripTaskRespons

typedef GPB_ENUM(BuyMarrySellTripTaskRespons_FieldNumber) {
  BuyMarrySellTripTaskRespons_FieldNumber_RetCode = 1,
  BuyMarrySellTripTaskRespons_FieldNumber_MarrySellTripTaskId = 2,
};

/**
 * 4.2 预约行程  返回
 **/
@interface BuyMarrySellTripTaskRespons : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 返回预约id暂时无用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *marrySellTripTaskId;

@end

#pragma mark - GetBuyOrderInfoRequest

typedef GPB_ENUM(GetBuyOrderInfoRequest_FieldNumber) {
  GetBuyOrderInfoRequest_FieldNumber_OrderId = 1,
};

/**
 * 获得待支付订单 ，当卖家同意预约订单后 就会返回 ??  此处 等第三模块调试在考虑
 * 专家查询订单信息（状态，1.支付后会以后台返回的支付成功为准）
 * 同一订单，卖家和买家能看到的数据是需要区分的，所以同样是订单信息，分卖家和买家2个接口
 * buy/getOrderInfo
 **/
@interface GetBuyOrderInfoRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@end

#pragma mark - GetBuyOrderInfoResponse

typedef GPB_ENUM(GetBuyOrderInfoResponse_FieldNumber) {
  GetBuyOrderInfoResponse_FieldNumber_RetCode = 1,
  GetBuyOrderInfoResponse_FieldNumber_OrderInfo = 2,
  GetBuyOrderInfoResponse_FieldNumber_Mes = 3,
};

@interface GetBuyOrderInfoResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

@property(nonatomic, readwrite, strong, null_resettable) OrderInfo *orderInfo;
/** Test to see if @c orderInfo has been set. */
@property(nonatomic, readwrite) BOOL hasOrderInfo;

/** 订单界面详情  按照需求 这里应该是要有各种信息的 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mes;

@end

#pragma mark - BuyTaskInfo

typedef GPB_ENUM(BuyTaskInfo_FieldNumber) {
  BuyTaskInfo_FieldNumber_Id_p = 1,
  BuyTaskInfo_FieldNumber_BuySpace = 2,
  BuyTaskInfo_FieldNumber_SpaceImageArray = 3,
  BuyTaskInfo_FieldNumber_StartAddresseeInfo = 4,
  BuyTaskInfo_FieldNumber_EndAddressInfo = 5,
  BuyTaskInfo_FieldNumber_DeadLineTime = 6,
  BuyTaskInfo_FieldNumber_BudgetMoney = 7,
};

@interface BuyTaskInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 买家需要寄送的货物 规格重量 */
@property(nonatomic, readwrite, strong, null_resettable) SpaceInfo *buySpace;
/** Test to see if @c buySpace has been set. */
@property(nonatomic, readwrite) BOOL hasBuySpace;

/** 包裹照片 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *spaceImageArray;
/** The number of items in @c spaceImageArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger spaceImageArray_Count;

/** 买家 包裹所在地址 寄送人信息 */
@property(nonatomic, readwrite, strong, null_resettable) AddresseeInfo *startAddresseeInfo;
/** Test to see if @c startAddresseeInfo has been set. */
@property(nonatomic, readwrite) BOOL hasStartAddresseeInfo;

/** 买家 包裹需要寄到的地址 收件人信息 */
@property(nonatomic, readwrite, strong, null_resettable) AddresseeInfo *endAddressInfo;
/** Test to see if @c endAddressInfo has been set. */
@property(nonatomic, readwrite) BOOL hasEndAddressInfo;

/** 买家要求的最迟的货物寄到目的地的时间 */
@property(nonatomic, readwrite) int32_t deadLineTime;

/** 预算价格 ？  币种转换 得考虑 系统子酸 ，到时候这个用一个实体，价格跟币种绑定使用 */
@property(nonatomic, readwrite) double budgetMoney;

@end

#pragma mark - SellTripTask

typedef GPB_ENUM(SellTripTask_FieldNumber) {
  SellTripTask_FieldNumber_TripTaskid = 1,
  SellTripTask_FieldNumber_StartAddress = 2,
  SellTripTask_FieldNumber_EndAddressInfo = 3,
  SellTripTask_FieldNumber_BeginTime = 4,
  SellTripTask_FieldNumber_EndTime = 5,
  SellTripTask_FieldNumber_ConsignSpace = 6,
  SellTripTask_FieldNumber_HandbagSpace = 7,
  SellTripTask_FieldNumber_OrderId = 8,
};

/**
 * 卖家的行程任务
 **/
@interface SellTripTask : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *tripTaskid;

/** 卖家行程开始地址 */
@property(nonatomic, readwrite, strong, null_resettable) AddressInfo *startAddress;
/** Test to see if @c startAddress has been set. */
@property(nonatomic, readwrite) BOOL hasStartAddress;

/** 卖家行程结束地址 */
@property(nonatomic, readwrite, strong, null_resettable) AddresseeInfo *endAddressInfo;
/** Test to see if @c endAddressInfo has been set. */
@property(nonatomic, readwrite) BOOL hasEndAddressInfo;

/** 卖家行程开始时间 */
@property(nonatomic, readwrite) int64_t beginTime;

/** 卖家行程结束时间 */
@property(nonatomic, readwrite) int64_t endTime;

/** 行程任务空间 */
@property(nonatomic, readwrite, strong, null_resettable) SpaceInfo *consignSpace;
/** Test to see if @c consignSpace has been set. */
@property(nonatomic, readwrite) BOOL hasConsignSpace;

/** 手提包的space */
@property(nonatomic, readwrite, strong, null_resettable) SpaceInfo *handbagSpace;
/** Test to see if @c handbagSpace has been set. */
@property(nonatomic, readwrite) BOOL hasHandbagSpace;

/** 如果有，则返回 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
