// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/buytheway/protocol/cardauth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class RetCode;
GPB_ENUM_FWD_DECLARE(CardTypeEnum);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CardauthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface CardauthRoot : GPBRootObject
@end

#pragma mark - CheckUserCardAuthRequest

typedef GPB_ENUM(CheckUserCardAuthRequest_FieldNumber) {
  CheckUserCardAuthRequest_FieldNumber_UserBizid = 1,
};

/**
 * 判断用户是否进行身份认证通过 /cardauth/check
 **/
@interface CheckUserCardAuthRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *userBizid;

@end

#pragma mark - CheckUserCardAuthResponse

typedef GPB_ENUM(CheckUserCardAuthResponse_FieldNumber) {
  CheckUserCardAuthResponse_FieldNumber_RetCode = 1,
  CheckUserCardAuthResponse_FieldNumber_Status = 2,
  CheckUserCardAuthResponse_FieldNumber_RejectReason = 3,
};

@interface CheckUserCardAuthResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 1.审核中   2.已通过实名认证  3.认证未通过 */
@property(nonatomic, readwrite) int32_t status;

/** 如果未通过，原因描述 */
@property(nonatomic, readwrite) int32_t rejectReason;

@end

#pragma mark - UserCardAuthRequest

typedef GPB_ENUM(UserCardAuthRequest_FieldNumber) {
  UserCardAuthRequest_FieldNumber_UserBizid = 1,
  UserCardAuthRequest_FieldNumber_CardType = 2,
  UserCardAuthRequest_FieldNumber_CardName = 3,
  UserCardAuthRequest_FieldNumber_CardNo = 4,
  UserCardAuthRequest_FieldNumber_CardImagepU = 5,
  UserCardAuthRequest_FieldNumber_CardImageDown = 6,
  UserCardAuthRequest_FieldNumber_CardImageSelfie = 7,
  UserCardAuthRequest_FieldNumber_CardImageAtt1 = 8,
};

/**
 * 用户发起身份认证 /cardauth/create
 **/
@interface UserCardAuthRequest : GPBMessage

/** 用户id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *userBizid;

/** 证件类型 */
@property(nonatomic, readwrite) enum CardTypeEnum cardType;

/** 证件名字，如身份证名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cardName;

/** 证件号码 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cardNo;

/** 证件正面图片 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cardImagepU;

/** 证件反面照片 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cardImageDown;

/** 手持证件照片 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cardImageSelfie;

/** 扩展字段 不管 Card_image_att1 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cardImageAtt1;

@end

/**
 * Fetches the raw value of a @c UserCardAuthRequest's @c cardType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t UserCardAuthRequest_CardType_RawValue(UserCardAuthRequest *message);
/**
 * Sets the raw value of an @c UserCardAuthRequest's @c cardType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetUserCardAuthRequest_CardType_RawValue(UserCardAuthRequest *message, int32_t value);

#pragma mark - UserCardAuthResponse

typedef GPB_ENUM(UserCardAuthResponse_FieldNumber) {
  UserCardAuthResponse_FieldNumber_RetCode = 1,
};

/**
 * 用户发起身份认证 保存结果
 **/
@interface UserCardAuthResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
