// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/buytheway/protocol/sell.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "com/buytheway/protocol/Sell.pbobjc.h"
 #import "com/buytheway/protocol/Common.pbobjc.h"
 #import "com/buytheway/protocol/Business.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - SellRoot

@implementation SellRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - SellRoot_FileDescriptor

static GPBFileDescriptor *SellRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"com.buytheway.protocol"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - SearchFlightInfoRequest

@implementation SearchFlightInfoRequest

@dynamic keyword;

typedef struct SearchFlightInfoRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *keyword;
} SearchFlightInfoRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "keyword",
        .dataTypeSpecific.className = NULL,
        .number = SearchFlightInfoRequest_FieldNumber_Keyword,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SearchFlightInfoRequest__storage_, keyword),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SearchFlightInfoRequest class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SearchFlightInfoRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - SearchFlightInfoResponse

@implementation SearchFlightInfoResponse

@dynamic flightInfoArray, flightInfoArray_Count;

typedef struct SearchFlightInfoResponse__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *flightInfoArray;
} SearchFlightInfoResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "flightInfoArray",
        .dataTypeSpecific.className = GPBStringifySymbol(FlightInfo),
        .number = SearchFlightInfoResponse_FieldNumber_FlightInfoArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(SearchFlightInfoResponse__storage_, flightInfoArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SearchFlightInfoResponse class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SearchFlightInfoResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\000flightInfo\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - SellTripTaskRequest

@implementation SellTripTaskRequest

@dynamic hasTaskInfo, taskInfo;

typedef struct SellTripTaskRequest__storage_ {
  uint32_t _has_storage_[1];
  MySaleTripTask *taskInfo;
} SellTripTaskRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "taskInfo",
        .dataTypeSpecific.className = GPBStringifySymbol(MySaleTripTask),
        .number = SellTripTaskRequest_FieldNumber_TaskInfo,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SellTripTaskRequest__storage_, taskInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SellTripTaskRequest class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SellTripTaskRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\010\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - SellReplyTripTaskRequest

@implementation SellReplyTripTaskRequest

@dynamic marrySellTripTaskId;
@dynamic answer;
@dynamic mes;

typedef struct SellReplyTripTaskRequest__storage_ {
  uint32_t _has_storage_[1];
  MesCode mes;
  NSString *marrySellTripTaskId;
} SellReplyTripTaskRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "marrySellTripTaskId",
        .dataTypeSpecific.className = NULL,
        .number = SellReplyTripTaskRequest_FieldNumber_MarrySellTripTaskId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SellReplyTripTaskRequest__storage_, marrySellTripTaskId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "answer",
        .dataTypeSpecific.className = NULL,
        .number = SellReplyTripTaskRequest_FieldNumber_Answer,
        .hasIndex = 1,
        .offset = 2,  // Stored in _has_storage_ to save space.
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeBool,
      },
      {
        .name = "mes",
        .dataTypeSpecific.enumDescFunc = MesCode_EnumDescriptor,
        .number = SellReplyTripTaskRequest_FieldNumber_Mes,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(SellReplyTripTaskRequest__storage_, mes),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SellReplyTripTaskRequest class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SellReplyTripTaskRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\023\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t SellReplyTripTaskRequest_Mes_RawValue(SellReplyTripTaskRequest *message) {
  GPBDescriptor *descriptor = [SellReplyTripTaskRequest descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:SellReplyTripTaskRequest_FieldNumber_Mes];
  return GPBGetMessageInt32Field(message, field);
}

void SetSellReplyTripTaskRequest_Mes_RawValue(SellReplyTripTaskRequest *message, int32_t value) {
  GPBDescriptor *descriptor = [SellReplyTripTaskRequest descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:SellReplyTripTaskRequest_FieldNumber_Mes];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

#pragma mark - GetSaleOrderInfoRequest

@implementation GetSaleOrderInfoRequest

@dynamic orderId;

typedef struct GetSaleOrderInfoRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *orderId;
} GetSaleOrderInfoRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "orderId",
        .dataTypeSpecific.className = NULL,
        .number = GetSaleOrderInfoRequest_FieldNumber_OrderId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetSaleOrderInfoRequest__storage_, orderId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetSaleOrderInfoRequest class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetSaleOrderInfoRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\007\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - GetSaleOrderInfoResponse

@implementation GetSaleOrderInfoResponse

@dynamic hasRetCode, retCode;
@dynamic hasOrderInfo, orderInfo;
@dynamic mes;

typedef struct GetSaleOrderInfoResponse__storage_ {
  uint32_t _has_storage_[1];
  RetCode *retCode;
  OrderInfo *orderInfo;
  NSString *mes;
} GetSaleOrderInfoResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "retCode",
        .dataTypeSpecific.className = GPBStringifySymbol(RetCode),
        .number = GetSaleOrderInfoResponse_FieldNumber_RetCode,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetSaleOrderInfoResponse__storage_, retCode),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "orderInfo",
        .dataTypeSpecific.className = GPBStringifySymbol(OrderInfo),
        .number = GetSaleOrderInfoResponse_FieldNumber_OrderInfo,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GetSaleOrderInfoResponse__storage_, orderInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "mes",
        .dataTypeSpecific.className = NULL,
        .number = GetSaleOrderInfoResponse_FieldNumber_Mes,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GetSaleOrderInfoResponse__storage_, mes),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetSaleOrderInfoResponse class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetSaleOrderInfoResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\001\007\000\002\t\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - SearchCityRequest

@implementation SearchCityRequest

@dynamic keyword;

typedef struct SearchCityRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *keyword;
} SearchCityRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "keyword",
        .dataTypeSpecific.className = NULL,
        .number = SearchCityRequest_FieldNumber_Keyword,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(SearchCityRequest__storage_, keyword),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SearchCityRequest class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SearchCityRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CommonCityRequest

@implementation CommonCityRequest

@dynamic keyword;

typedef struct CommonCityRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *keyword;
} CommonCityRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "keyword",
        .dataTypeSpecific.className = NULL,
        .number = CommonCityRequest_FieldNumber_Keyword,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CommonCityRequest__storage_, keyword),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CommonCityRequest class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CommonCityRequest__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - SearchCityResponse

@implementation SearchCityResponse

@dynamic cityInfoArray, cityInfoArray_Count;

typedef struct SearchCityResponse__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *cityInfoArray;
} SearchCityResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "cityInfoArray",
        .dataTypeSpecific.className = GPBStringifySymbol(CityInfo),
        .number = SearchCityResponse_FieldNumber_CityInfoArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(SearchCityResponse__storage_, cityInfoArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[SearchCityResponse class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(SearchCityResponse__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\001\001\000cityInfo\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - MySaleTripTask

@implementation MySaleTripTask

@dynamic id_p;
@dynamic hasFlightInfo, flightInfo;
@dynamic hasConsignSpace, consignSpace;
@dynamic hasHandbagSpace, handbagSpace;
@dynamic deadLineTime;
@dynamic hasAddress, address;
@dynamic hasConsigneePhone, consigneePhone;
@dynamic consigneeName;
@dynamic orderIdArray, orderIdArray_Count;

typedef struct MySaleTripTask__storage_ {
  uint32_t _has_storage_[1];
  int32_t deadLineTime;
  NSString *id_p;
  FlightInfo *flightInfo;
  SpaceInfo *consignSpace;
  SpaceInfo *handbagSpace;
  AddressInfo *address;
  PhoneNumber *consigneePhone;
  NSString *consigneeName;
  NSMutableArray *orderIdArray;
} MySaleTripTask__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "id_p",
        .dataTypeSpecific.className = NULL,
        .number = MySaleTripTask_FieldNumber_Id_p,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(MySaleTripTask__storage_, id_p),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "flightInfo",
        .dataTypeSpecific.className = GPBStringifySymbol(FlightInfo),
        .number = MySaleTripTask_FieldNumber_FlightInfo,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(MySaleTripTask__storage_, flightInfo),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "consignSpace",
        .dataTypeSpecific.className = GPBStringifySymbol(SpaceInfo),
        .number = MySaleTripTask_FieldNumber_ConsignSpace,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(MySaleTripTask__storage_, consignSpace),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "handbagSpace",
        .dataTypeSpecific.className = GPBStringifySymbol(SpaceInfo),
        .number = MySaleTripTask_FieldNumber_HandbagSpace,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(MySaleTripTask__storage_, handbagSpace),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "deadLineTime",
        .dataTypeSpecific.className = NULL,
        .number = MySaleTripTask_FieldNumber_DeadLineTime,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(MySaleTripTask__storage_, deadLineTime),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "address",
        .dataTypeSpecific.className = GPBStringifySymbol(AddressInfo),
        .number = MySaleTripTask_FieldNumber_Address,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(MySaleTripTask__storage_, address),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "consigneePhone",
        .dataTypeSpecific.className = GPBStringifySymbol(PhoneNumber),
        .number = MySaleTripTask_FieldNumber_ConsigneePhone,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(MySaleTripTask__storage_, consigneePhone),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "consigneeName",
        .dataTypeSpecific.className = NULL,
        .number = MySaleTripTask_FieldNumber_ConsigneeName,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(MySaleTripTask__storage_, consigneeName),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "orderIdArray",
        .dataTypeSpecific.className = NULL,
        .number = MySaleTripTask_FieldNumber_OrderIdArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(MySaleTripTask__storage_, orderIdArray),
        .flags = (GPBFieldFlags)(GPBFieldRepeated | GPBFieldTextFormatNameCustom),
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[MySaleTripTask class]
                                     rootClass:[SellRoot class]
                                          file:SellRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(MySaleTripTask__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\007\002\n\000\003\014\000\004\014\000\005\014\000\007\016\000\010\r\000\n\000orderId\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
