// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/buytheway/protocol/sell.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AddressInfo;
@class CityInfo;
@class FlightInfo;
@class MySaleTripTask;
@class OrderInfo;
@class PhoneNumber;
@class RetCode;
@class SpaceInfo;
GPB_ENUM_FWD_DECLARE(MesCode);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - SellRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface SellRoot : GPBRootObject
@end

#pragma mark - SearchFlightInfoRequest

typedef GPB_ENUM(SearchFlightInfoRequest_FieldNumber) {
  SearchFlightInfoRequest_FieldNumber_Keyword = 1,
};

/**
 * 获取航班信息  /sell/flight/search
 **/
@interface SearchFlightInfoRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

@end

#pragma mark - SearchFlightInfoResponse

typedef GPB_ENUM(SearchFlightInfoResponse_FieldNumber) {
  SearchFlightInfoResponse_FieldNumber_FlightInfoArray = 1,
};

/**
 * 获取航班信息返回对象
 **/
@interface SearchFlightInfoResponse : GPBMessage

/** 返回航班信息列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<FlightInfo*> *flightInfoArray;
/** The number of items in @c flightInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger flightInfoArray_Count;

@end

#pragma mark - SellTripTaskRequest

typedef GPB_ENUM(SellTripTaskRequest_FieldNumber) {
  SellTripTaskRequest_FieldNumber_TaskInfo = 1,
};

/**
 * 卖家发布行程（航班）信息 ，space等；即 行程任务信息 定义为TripTask   /sell/tripTask
 **/
@interface SellTripTaskRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) MySaleTripTask *taskInfo;
/** Test to see if @c taskInfo has been set. */
@property(nonatomic, readwrite) BOOL hasTaskInfo;

@end

#pragma mark - SellReplyTripTaskRequest

typedef GPB_ENUM(SellReplyTripTaskRequest_FieldNumber) {
  SellReplyTripTaskRequest_FieldNumber_MarrySellTripTaskId = 1,
  SellReplyTripTaskRequest_FieldNumber_Answer = 2,
  SellReplyTripTaskRequest_FieldNumber_Mes = 3,
};

/**
 * 卖家 回复买家预约的 /sell/sellReplyTripTask
 **/
@interface SellReplyTripTaskRequest : GPBMessage

/** 买家预约任务id */
@property(nonatomic, readwrite, copy, null_resettable) NSString *marrySellTripTaskId;

/** 回复结果  true代表同意 */
@property(nonatomic, readwrite) BOOL answer;

/** 拒绝原因这里 */
@property(nonatomic, readwrite) enum MesCode mes;

@end

/**
 * Fetches the raw value of a @c SellReplyTripTaskRequest's @c mes property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t SellReplyTripTaskRequest_Mes_RawValue(SellReplyTripTaskRequest *message);
/**
 * Sets the raw value of an @c SellReplyTripTaskRequest's @c mes property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetSellReplyTripTaskRequest_Mes_RawValue(SellReplyTripTaskRequest *message, int32_t value);

#pragma mark - GetSaleOrderInfoRequest

typedef GPB_ENUM(GetSaleOrderInfoRequest_FieldNumber) {
  GetSaleOrderInfoRequest_FieldNumber_OrderId = 1,
};

/**
 * /sale/getOrderInfo
 **/
@interface GetSaleOrderInfoRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *orderId;

@end

#pragma mark - GetSaleOrderInfoResponse

typedef GPB_ENUM(GetSaleOrderInfoResponse_FieldNumber) {
  GetSaleOrderInfoResponse_FieldNumber_RetCode = 1,
  GetSaleOrderInfoResponse_FieldNumber_OrderInfo = 2,
  GetSaleOrderInfoResponse_FieldNumber_Mes = 3,
};

@interface GetSaleOrderInfoResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

@property(nonatomic, readwrite, strong, null_resettable) OrderInfo *orderInfo;
/** Test to see if @c orderInfo has been set. */
@property(nonatomic, readwrite) BOOL hasOrderInfo;

/** 订单界面详情  按照需求 这里应该是要有各种信息的 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *mes;

@end

#pragma mark - SearchCityRequest

typedef GPB_ENUM(SearchCityRequest_FieldNumber) {
  SearchCityRequest_FieldNumber_Keyword = 1,
};

/**
 * 城市搜索 /sell/searchcity
 **/
@interface SearchCityRequest : GPBMessage

/** city搜索 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

@end

#pragma mark - CommonCityRequest

typedef GPB_ENUM(CommonCityRequest_FieldNumber) {
  CommonCityRequest_FieldNumber_Keyword = 1,
};

/**
 * 常用城市搜索 请求/sell/common/searchcity
 **/
@interface CommonCityRequest : GPBMessage

/** city搜索 为空搜索全部,此参数用来控制以后根据定位到哪个国家进行搜索的 本次需求不用 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

@end

#pragma mark - SearchCityResponse

typedef GPB_ENUM(SearchCityResponse_FieldNumber) {
  SearchCityResponse_FieldNumber_CityInfoArray = 1,
};

/**
 * 城市搜索返回结果  /sell/searchcity  /sell/common/searchcity  俩个请求公用返回
 **/
@interface SearchCityResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<CityInfo*> *cityInfoArray;
/** The number of items in @c cityInfoArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cityInfoArray_Count;

@end

#pragma mark - MySaleTripTask

typedef GPB_ENUM(MySaleTripTask_FieldNumber) {
  MySaleTripTask_FieldNumber_Id_p = 1,
  MySaleTripTask_FieldNumber_FlightInfo = 2,
  MySaleTripTask_FieldNumber_ConsignSpace = 3,
  MySaleTripTask_FieldNumber_HandbagSpace = 4,
  MySaleTripTask_FieldNumber_DeadLineTime = 5,
  MySaleTripTask_FieldNumber_Address = 6,
  MySaleTripTask_FieldNumber_ConsigneePhone = 7,
  MySaleTripTask_FieldNumber_ConsigneeName = 8,
  MySaleTripTask_FieldNumber_OrderIdArray = 10,
};

@interface MySaleTripTask : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *id_p;

/** 航班信息 */
@property(nonatomic, readwrite, strong, null_resettable) FlightInfo *flightInfo;
/** Test to see if @c flightInfo has been set. */
@property(nonatomic, readwrite) BOOL hasFlightInfo;

/** 可以托运的space */
@property(nonatomic, readwrite, strong, null_resettable) SpaceInfo *consignSpace;
/** Test to see if @c consignSpace has been set. */
@property(nonatomic, readwrite) BOOL hasConsignSpace;

/** 手提包的space */
@property(nonatomic, readwrite, strong, null_resettable) SpaceInfo *handbagSpace;
/** Test to see if @c handbagSpace has been set. */
@property(nonatomic, readwrite) BOOL hasHandbagSpace;

/** 卖家要求的最迟的货物交付时间，买家必须将货物在此时间交付给卖家，一般是航程开始时多少小时 */
@property(nonatomic, readwrite) int32_t deadLineTime;

/** 买家所属地址 */
@property(nonatomic, readwrite, strong, null_resettable) AddressInfo *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

/** 收货人用户电话 */
@property(nonatomic, readwrite, strong, null_resettable) PhoneNumber *consigneePhone;
/** Test to see if @c consigneePhone has been set. */
@property(nonatomic, readwrite) BOOL hasConsigneePhone;

/** 收货人姓名 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *consigneeName;

/** 一个行程可以绑定多个需求id */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *orderIdArray;
/** The number of items in @c orderIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger orderIdArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
