// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/buytheway/protocol/village.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class Comment;
@class Location;
@class PostOfVillage;
@class RetCode;
@class Village;
@class Villager;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - VillageRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface VillageRoot : GPBRootObject
@end

#pragma mark - GetVillageListRequest

typedef GPB_ENUM(GetVillageListRequest_FieldNumber) {
  GetVillageListRequest_FieldNumber_OwnerId = 1,
  GetVillageListRequest_FieldNumber_Location = 2,
  GetVillageListRequest_FieldNumber_Keyword = 3,
  GetVillageListRequest_FieldNumber_Joined = 4,
};

/**
 * 1.1. 取村庄列表请求
 * 接口地址  /village/list
 **/
@interface GetVillageListRequest : GPBMessage

/** 以下条件 为4选1，也能处理过多重滤条件的情况，视需求而定 */
@property(nonatomic, readwrite) int64_t ownerId;

/** 如果有值 ，则根据位置过滤（取附近的村庄） */
@property(nonatomic, readwrite, strong, null_resettable) Location *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

/** 搜索关键字，如果有值，则根据关键字搜索 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

/** 如果有值（为true),则表示取我加入了的村庄列表， */
@property(nonatomic, readwrite) BOOL joined;

@end

#pragma mark - GetVillageListResponse

typedef GPB_ENUM(GetVillageListResponse_FieldNumber) {
  GetVillageListResponse_FieldNumber_RetCode = 1,
  GetVillageListResponse_FieldNumber_VillagesArray = 2,
};

/**
 * 取村庄列表返回
 **/
@interface GetVillageListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 村庄列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Village*> *villagesArray;
/** The number of items in @c villagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger villagesArray_Count;

@end

#pragma mark - VillageRequest

typedef GPB_ENUM(VillageRequest_FieldNumber) {
  VillageRequest_FieldNumber_Location = 1,
  VillageRequest_FieldNumber_Name = 2,
  VillageRequest_FieldNumber_Logo = 3,
  VillageRequest_FieldNumber_Cover = 4,
};

/**
 * 1.2. 创建村庄 请求
 * 接口地址  /village/create
 * 接口地址  /village/update
 **/
@interface VillageRequest : GPBMessage

/** 村庄的位置 */
@property(nonatomic, readwrite, strong, null_resettable) Location *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

/** 村庄名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 村庄的logo */
@property(nonatomic, readwrite, copy, null_resettable) NSString *logo;

/** 村庄的大图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cover;

@end

#pragma mark - VillageResponse

typedef GPB_ENUM(VillageResponse_FieldNumber) {
  VillageResponse_FieldNumber_RetCode = 1,
  VillageResponse_FieldNumber_VillageIdArray = 2,
};

/**
 * 取村庄列表返回
 **/
@interface VillageResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 新创建的村庄id */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *villageIdArray;
/** The number of items in @c villageIdArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger villageIdArray_Count;

@end

#pragma mark - GetVillagerIdListRequest

typedef GPB_ENUM(GetVillagerIdListRequest_FieldNumber) {
  GetVillagerIdListRequest_FieldNumber_VillageId = 1,
  GetVillagerIdListRequest_FieldNumber_Keyword = 2,
};

/**
 * 2.1. 村民id列表请求
 * 接口地址  /village/villager/list
 **/
@interface GetVillagerIdListRequest : GPBMessage

/** 村庄id，加入，发贴都需要带上村庄id */
@property(nonatomic, readwrite) int64_t villageId;

/** 搜索的关键字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *keyword;

@end

#pragma mark - GetVillagerIdListResponse

typedef GPB_ENUM(GetVillagerIdListResponse_FieldNumber) {
  GetVillagerIdListResponse_FieldNumber_RetCode = 1,
  GetVillagerIdListResponse_FieldNumber_VillagersArray = 2,
};

/**
 * 村民列表返回
 **/
@interface GetVillagerIdListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 村民用户id列表 */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *villagersArray;
/** The number of items in @c villagersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger villagersArray_Count;

@end

#pragma mark - GetVillagerInfoListRequest

typedef GPB_ENUM(GetVillagerInfoListRequest_FieldNumber) {
  GetVillagerInfoListRequest_FieldNumber_VillagersArray = 1,
};

/**
 * 2.2. 村民信息列表请求
 * 接口地址  /village/villager/info
 **/
@interface GetVillagerInfoListRequest : GPBMessage

/** 村民id list */
@property(nonatomic, readwrite, strong, null_resettable) GPBInt64Array *villagersArray;
/** The number of items in @c villagersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger villagersArray_Count;

@end

#pragma mark - GetVillagerInfoListResponse

typedef GPB_ENUM(GetVillagerInfoListResponse_FieldNumber) {
  GetVillagerInfoListResponse_FieldNumber_RetCode = 1,
  GetVillagerInfoListResponse_FieldNumber_VillagersArray = 2,
};

/**
 * 村民信息列表返回
 **/
@interface GetVillagerInfoListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 村民用户id列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Villager*> *villagersArray;
/** The number of items in @c villagersArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger villagersArray_Count;

@end

#pragma mark - JoinVillageRequest

typedef GPB_ENUM(JoinVillageRequest_FieldNumber) {
  JoinVillageRequest_FieldNumber_VillageId = 1,
};

/**
 * 2.2. 加入村庄请求,注意，不需要传用户自己的id，通信的token，已有全部信息
 * 接口地址  /village/villager/join
 **/
@interface JoinVillageRequest : GPBMessage

/** 村庄id，加入，发贴都需要带上村庄id */
@property(nonatomic, readwrite) int64_t villageId;

@end

#pragma mark - JoinVillageResponse

typedef GPB_ENUM(JoinVillageResponse_FieldNumber) {
  JoinVillageResponse_FieldNumber_RetCode = 1,
};

/**
 * 加入村庄返回
 **/
@interface JoinVillageResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

@end

#pragma mark - GetVillagePostListRequest

typedef GPB_ENUM(GetVillagePostListRequest_FieldNumber) {
  GetVillagePostListRequest_FieldNumber_VillageId = 1,
  GetVillagePostListRequest_FieldNumber_TopId = 2,
  GetVillagePostListRequest_FieldNumber_BottomId = 3,
  GetVillagePostListRequest_FieldNumber_Direction = 4,
};

/**
 * 3.1. 村子帖子列表请求
 * 为增强服务器稳定性，（防止客户端传pageSizef无穷大），分页大小由服务器控制
 * 接口地址  /village/posts/list
 **/
@interface GetVillagePostListRequest : GPBMessage

/** 村庄id，加入，发贴都需要带上村庄id */
@property(nonatomic, readwrite) int64_t villageId;

/** 本地已取回的，顶部的帖子id */
@property(nonatomic, readwrite) int64_t topId;

/** 本地已取回的，底部的帖子id */
@property(nonatomic, readwrite) int64_t bottomId;

/**
 * * 加载方向，0：下拉刷新（向上加载）  1：底部加载更多
 * 如果下拉刷新的时候 topId和服务器的最新id一样，则不下发任何数据！
 * 如果底部加载的时候 bottomId和服务器的最老的帖子id一样，则不下发任何数据！
 **/
@property(nonatomic, readwrite) int32_t direction;

@end

#pragma mark - GetVillagePostListResponse

typedef GPB_ENUM(GetVillagePostListResponse_FieldNumber) {
  GetVillagePostListResponse_FieldNumber_RetCode = 1,
  GetVillagePostListResponse_FieldNumber_PostsArray = 2,
};

/**
 * 村子帖子列表返回
 **/
@interface GetVillagePostListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 村民用户id列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PostOfVillage*> *postsArray;
/** The number of items in @c postsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger postsArray_Count;

@end

#pragma mark - PostLikeRequest

typedef GPB_ENUM(PostLikeRequest_FieldNumber) {
  PostLikeRequest_FieldNumber_PostId = 1,
};

/**
 * 3.2. 点赞请求
 * 接口地址  /village/posts/like
 **/
@interface PostLikeRequest : GPBMessage

/**  帖子id */
@property(nonatomic, readwrite) int64_t postId;

@end

#pragma mark - PostLikeResponse

typedef GPB_ENUM(PostLikeResponse_FieldNumber) {
  PostLikeResponse_FieldNumber_RetCode = 1,
};

/**
 * 点赞的返回
 **/
@interface PostLikeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

@end

#pragma mark - PostAddRequest

typedef GPB_ENUM(PostAddRequest_FieldNumber) {
  PostAddRequest_FieldNumber_VillageId = 1,
  PostAddRequest_FieldNumber_Content = 2,
  PostAddRequest_FieldNumber_ImagesArray = 3,
  PostAddRequest_FieldNumber_Address = 4,
};

/**
 * 3.3. 发贴请求
 * 接口地址  /village/posts/add
 **/
@interface PostAddRequest : GPBMessage

/**  村庄id */
@property(nonatomic, readwrite) int64_t villageId;

/** 帖子的文字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 帖子的图片列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *imagesArray;
/** The number of items in @c imagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

/** 发贴地址 */
@property(nonatomic, readwrite, strong, null_resettable) Location *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

#pragma mark - PostAddResponse

typedef GPB_ENUM(PostAddResponse_FieldNumber) {
  PostAddResponse_FieldNumber_RetCode = 1,
  PostAddResponse_FieldNumber_PostId = 2,
};

/**
 * 发贴的返回
 **/
@interface PostAddResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 该条帖子的id */
@property(nonatomic, readwrite) int64_t postId;

@end

#pragma mark - AddCommentRequest

typedef GPB_ENUM(AddCommentRequest_FieldNumber) {
  AddCommentRequest_FieldNumber_PostId = 1,
  AddCommentRequest_FieldNumber_Centent = 2,
  AddCommentRequest_FieldNumber_TargeName = 3,
};

/**
 * 4.1. 发评论请求
 * 接口地址  /village/comment/add
 **/
@interface AddCommentRequest : GPBMessage

/**  帖子id */
@property(nonatomic, readwrite) int64_t postId;

/** 评论内容 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *centent;

/** \@对评论进行评论 ， 可以为空 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *targeName;

@end

#pragma mark - AddCommentResponse

typedef GPB_ENUM(AddCommentResponse_FieldNumber) {
  AddCommentResponse_FieldNumber_RetCode = 1,
  AddCommentResponse_FieldNumber_CommentId = 2,
};

/**
 * 发评论的返回
 **/
@interface AddCommentResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

/** 发布成功的帖子id */
@property(nonatomic, readwrite) int64_t commentId;

@end

#pragma mark - CommentListRequest

typedef GPB_ENUM(CommentListRequest_FieldNumber) {
  CommentListRequest_FieldNumber_PostId = 1,
  CommentListRequest_FieldNumber_TopId = 2,
  CommentListRequest_FieldNumber_BottomId = 3,
  CommentListRequest_FieldNumber_Direction = 4,
};

/**
 * 4.3. 评论列表请求
 * 接口地址  /village/comment/list
 **/
@interface CommentListRequest : GPBMessage

/**  帖子id */
@property(nonatomic, readwrite) int64_t postId;

/** 本地已取回的，顶部的帖子id */
@property(nonatomic, readwrite) int64_t topId;

/** 本地已取回的，底部的帖子id */
@property(nonatomic, readwrite) int64_t bottomId;

/**
 * * 加载方向，0：下拉刷新（向上加载）  1：底部加载更多
 * 如果下拉刷新的时候 topId和服务器的最新id一样，则不下发任何数据！
 * 如果底部加载的时候 bottomId和服务器的最老的帖子id一样，则不下发任何数据！
 **/
@property(nonatomic, readwrite) int32_t direction;

@end

#pragma mark - CommentListResponse

typedef GPB_ENUM(CommentListResponse_FieldNumber) {
  CommentListResponse_FieldNumber_RetCode = 1,
  CommentListResponse_FieldNumber_CommentsArray = 2,
};

/**
 * 评论列表返回
 **/
@interface CommentListResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) RetCode *retCode;
/** Test to see if @c retCode has been set. */
@property(nonatomic, readwrite) BOOL hasRetCode;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Comment*> *commentsArray;
/** The number of items in @c commentsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger commentsArray_Count;

@end

#pragma mark - Location

typedef GPB_ENUM(Location_FieldNumber) {
  Location_FieldNumber_Longitute = 1,
  Location_FieldNumber_Latitute = 2,
  Location_FieldNumber_Address = 3,
};

/**
 * 表示地理位置的实体类
 **/
@interface Location : GPBMessage

/** 纬度 */
@property(nonatomic, readwrite) double longitute;

/** 纬度 */
@property(nonatomic, readwrite) double latitute;

/** 地址名称 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *address;

@end

#pragma mark - Villager

typedef GPB_ENUM(Villager_FieldNumber) {
  Villager_FieldNumber_Id_p = 1,
  Villager_FieldNumber_Name = 2,
  Villager_FieldNumber_Avatar = 3,
};

/**
 * 村民的实体类
 **/
@interface Villager : GPBMessage

/** 村庄id，加入，发贴都需要带上村庄id */
@property(nonatomic, readwrite) int64_t id_p;

/** 名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 头像 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *avatar;

@end

#pragma mark - Village

typedef GPB_ENUM(Village_FieldNumber) {
  Village_FieldNumber_Id_p = 1,
  Village_FieldNumber_Location = 2,
  Village_FieldNumber_Name = 3,
  Village_FieldNumber_Logo = 4,
  Village_FieldNumber_Cover = 5,
  Village_FieldNumber_VillageHeadName = 6,
  Village_FieldNumber_VillageHeadId = 7,
  Village_FieldNumber_VillagerCount = 8,
};

/**
 * 村庄的实体类
 **/
@interface Village : GPBMessage

/** 村庄id，加入，发贴都需要带上村庄id */
@property(nonatomic, readwrite) int64_t id_p;

/** 村庄的位置 */
@property(nonatomic, readwrite, strong, null_resettable) Location *location;
/** Test to see if @c location has been set. */
@property(nonatomic, readwrite) BOOL hasLocation;

/** 村庄名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** 村庄的logo */
@property(nonatomic, readwrite, copy, null_resettable) NSString *logo;

/** 村庄的大图 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *cover;

/** 村长的名字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *villageHeadName;

/** 村长的user id */
@property(nonatomic, readwrite) int64_t villageHeadId;

/** 村民数量 */
@property(nonatomic, readwrite) int32_t villagerCount;

@end

#pragma mark - PostOfVillage

typedef GPB_ENUM(PostOfVillage_FieldNumber) {
  PostOfVillage_FieldNumber_Id_p = 1,
  PostOfVillage_FieldNumber_PosterId = 2,
  PostOfVillage_FieldNumber_Content = 3,
  PostOfVillage_FieldNumber_ImagesArray = 4,
  PostOfVillage_FieldNumber_Time = 5,
  PostOfVillage_FieldNumber_Address = 6,
  PostOfVillage_FieldNumber_LikeCount = 7,
  PostOfVillage_FieldNumber_CommentCount = 8,
  PostOfVillage_FieldNumber_Liked = 9,
};

/**
 * 村庄的贴子
 **/
@interface PostOfVillage : GPBMessage

/** 帖子id，全局唯一 */
@property(nonatomic, readwrite) int64_t id_p;

/** 发贴者id，发贴人的头像等其它信息用其它接口去获取，本地根据uid作缓存 */
@property(nonatomic, readwrite) int64_t posterId;

/** 帖子的文字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 帖子的图片列表 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *imagesArray;
/** The number of items in @c imagesArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger imagesArray_Count;

/** 发帖时间 */
@property(nonatomic, readwrite) int64_t time;

/** 发贴地址 */
@property(nonatomic, readwrite, strong, null_resettable) Location *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

/** 点赞数 */
@property(nonatomic, readwrite) int32_t likeCount;

/** 评论数 */
@property(nonatomic, readwrite) int32_t commentCount;

/** 是否已点赞，需求是后台要作记录，则标志为true时不可再点 */
@property(nonatomic, readwrite) BOOL liked;

@end

#pragma mark - Comment

typedef GPB_ENUM(Comment_FieldNumber) {
  Comment_FieldNumber_Id_p = 1,
  Comment_FieldNumber_PosterId = 2,
  Comment_FieldNumber_Content = 3,
  Comment_FieldNumber_Time = 4,
  Comment_FieldNumber_Address = 5,
};

/**
 * 某条贴子的评论
 **/
@interface Comment : GPBMessage

/** 评论id，全局唯一 */
@property(nonatomic, readwrite) int64_t id_p;

/** 发此条评论的人的id */
@property(nonatomic, readwrite) int64_t posterId;

/** 帖子的文字 */
@property(nonatomic, readwrite, copy, null_resettable) NSString *content;

/** 评论时间 */
@property(nonatomic, readwrite) int64_t time;

/** 评论地址 */
@property(nonatomic, readwrite, strong, null_resettable) Location *address;
/** Test to see if @c address has been set. */
@property(nonatomic, readwrite) BOOL hasAddress;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
